### PR TITLE
Added Hot Pixel JSON file to the calibration repository 

### PR DESCRIPTION
**Pull request by MYOMAO**
I added a JSON file named hot_pixel_mask.json in the folder Tracking/MVTX/ to allow masking hot pixels of the MVTX. This implementation is good for now and there will be further development to improve the hot pixel later.

### CODE REVIEW

**Comment by pinkenburg** [comment]
In the future - this just has to use the cdb. Leaving this file here and using it will just duplicate the work later. The sooner the switch the less disruption this will cause

**Comment by osbornjd** [comment]
We talked about putting this in here first and getting things organized, then just switching to the CDB since (as far as I know) you are the only one who can put files into the CDB, and we wanted to get things setup so that the switch could be made easily. If you want to put this in the CDB now then go for it

**Comment by pinkenburg** [comment]
It needs to be in CDBTTree format

**Comment by osbornjd** [comment]
Ah okay, so there is a uniform format that files in the CDB need to be. In that case we have two options based on the work that Zhaozhong already did at the workfest, which was to implement a hot dead pixel reader based on this JSON file. We could:

1. Have him open the PR into coresoftware to read this file and get that functional and into the main repo (he used another json reading package, so we need to switch to use lohmann since that is already in our nightly build). Then once that works, we can modify the format to match the CDB.
2. Just pause the development and put this json file into CDBTree format and figure out the development needed to read that in before making the PR into coresoftware.

**Comment by pinkenburg** [comment]
2 is the way to go, it is a minor effort to create this file (example macro is https://github.com/sPHENIX-Collaboration/macros/blob/master/CDBTest/TestCDBTTree.C, but can also be done in compiled code, however this file is being produced). Then it just needs two more lines in the readback code to fetch this from the cdb

**Comment by osbornjd** [comment]
So the example basically shows how to fill the tree with some random "calibrations," right? So @MYOMAO @cdean-github I guess we should write a macro to read in your JSON file using the existing infrastructure which then produces the CDBTree object, after which we can then read it into the MVTX unpacker and apply the maskings. Let's talk about it offline

**Comment by cdean-github** [comment]
I agree that having a more in depth discussion is needed. We do need to go to the CDB format but my wonder is, when we update the hot/dead pixel code to figure out the mask run-by-run when we look at the raw hits, do we generate the CDBTree in the raw hit writer then and read it back in the unpacker OR do write the hot mask to a run header in the raw hit writer then read that in the unpacker and create the CDBTree at that stage

**Comment by MYOMAO** [comment]
It is okay for me to use macro and make the JSON into the format that fits in the CDBTree object. We can discuss what to do next.

**Pull request merged**
