### PR TITLE
Updated with the most recent calibration files from EvtGen Developers

### PR DESCRIPTION
**Pull request by MYOMAO**
We have checked out the most recent version of the files DECAY.DEC and evt.pdl direct from the latest version of EvtGen. 

DECAY.DEC: https://gitlab.cern.ch/evtgen/evtgen/-/blob/master/DECAY.DEC

evt.pdl: https://gitlab.cern.ch/evtgen/evtgen/-/blob/master/evt.pdl

For the DECAY.DEC file, it is using PDG 2014 with some bugs fixed on the branching ratios of beauty and charm hadron decay, particularly on the semi-leptonic channels .

For the evt.pdl file, it has been updated to the recent version of PDG 2019.

### CODE REVIEW

**Comment by pinkenburg** [comment]
We should use DECAY.DEC and evt.pdl from the EvtGen installation. They are identical but the installed version is tagged and therefore we have better control over it. The other *.DEC files look like they come from some tests (100% branching ratios if I interpret them correctly). If that is the case - I am not sure if we want those in the calibrations repository

**Comment by cdean-github** [comment]
Hi @pinkenburg I agree that we should use the general files from the EvtGen installation so it's easily kept up to date. We should think if we want to have an EvtGen folder for custom dec files. We would use them to generate pure exclusive decays for certain analyses (e.g. B+ -> D0 pi+) and this way we can check the decay topology settings when we submit papers.

**Comment by blackcathj** [comment]
Let's edit this pull request to remove DECAY.DEC and evt.pdl , and edit https://github.com/sPHENIX-Collaboration/coresoftware/pull/1618 to load them from the EvtGen installation. 

Let's also keep the rest of the sample force decay configurations, so we can check specific decays and use them as example in the future.

**Comment by MYOMAO** [comment]
Ok now I have removed the DECAY.DEC and evt.pdl files here as Jin suggested

**Pull request merged**
